---
:console_log_remove: []
:console_log_add:
- :json
- :merge_conflict
- :migration
- :pry
- :rails
- :ruby
- :whitespace
- :yaml
:checks_remove: []
:checks_add:
- :common
- :console_log
- :json
- :merge_conflict
- :migration
- :pry
- :rails
- :ruby
- :whitespace
- :yaml
- :tabs
